version: 2

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - revive

linters-settings:
  typecheck:
    whole-program: true

issues:
  exclude-rules:
    - path: main.go
      text: "undefined: validator"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0