linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - revive  # Отключаем revive (включает проверку комментариев)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0