// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountLinkVisits(ctx context.Context) (int64, error)
	CountLinkVisitsByLinkID(ctx context.Context, linkID int32) (int64, error)
	CountLinks(ctx context.Context) (int64, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error)
	DeleteLink(ctx context.Context, id int32) error
	GetLink(ctx context.Context, id int32) (Link, error)
	GetLinkByShortName(ctx context.Context, shortName string) (Link, error)
	GetLinkVisits(ctx context.Context, arg GetLinkVisitsParams) ([]LinkVisit, error)
	GetLinkVisitsByLinkID(ctx context.Context, arg GetLinkVisitsByLinkIDParams) ([]LinkVisit, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
