// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountLinks(ctx context.Context) (int64, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	DeleteLink(ctx context.Context, id int32) error
	GetLink(ctx context.Context, id int32) (Link, error)
	GetLinkByShortName(ctx context.Context, shortName string) (Link, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
